# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-08 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20, verbose_name='\u73ed\u7ea7\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u73ed\u7ea7',
                'verbose_name_plural': '\u73ed\u7ea7\u8868',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u5b66\u751f\u59d3\u540d')),
                ('age', models.IntegerField(verbose_name='\u5e74\u9f84')),
                ('allclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Allclass')),
            ],
            options={
                'verbose_name': '\u5b66\u751f',
                'verbose_name_plural': '\u5b66\u751f\u8868',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_name', models.CharField(max_length=20, verbose_name='\u6559\u5e08\u540d\u79f0')),
                ('sex', models.IntegerField(choices=[(0, '\u7537'), (1, '\u5973'), (2, '\u672a\u77e5')], default=2, verbose_name='\u6027\u522b')),
            ],
            options={
                'verbose_name': '\u6559\u5e08',
                'verbose_name_plural': '\u6559\u5e08\u8868',
            },
        ),
        migrations.AddField(
            model_name='students',
            name='teacher',
            field=models.ManyToManyField(to='review.Teacher'),
        ),
        migrations.AddField(
            model_name='allclass',
            name='teacher',
            field=models.ManyToManyField(to='review.Teacher'),
        ),
    ]
