# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-03-08 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_remove_allclass_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='teacher',
        ),
        migrations.AddField(
            model_name='allclass',
            name='teacher',
            field=models.ManyToManyField(to='review.Teacher'),
        ),
    ]
