# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20180308_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='phone',
            field=models.IntegerField(default=None, verbose_name='\u7535\u8bdd'),
        ),
        migrations.AddField(
            model_name='students',
            name='sex',
            field=models.IntegerField(choices=[(0, '\u7537'), (1, '\u5973'), (2, '\u672a\u77e5')], default=2, verbose_name='\u6027\u522b'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=None, verbose_name='\u5e74\u9f84'),
        ),
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(default=None, verbose_name='\u5e74\u9f84'),
        ),
    ]
